apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-rbd-pvc
  namespace: rook-ceph
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: block-rbd-pod
  namespace: rook-ceph
spec:
  containers:
    - name: rocky
      image: rockylinux:9.3-minimal
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-rbd-pvc
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-rbd-pvc
  namespace: rook-ceph
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: fs-rbd-pod
  namespace: rook-ceph
spec:
  containers:
    - name: web
      image: nginx
      volumeMounts:
        - name: fs-pvc
          mountPath: /var/lib/www/html
  volumes:
    - name: fs-pvc
      persistentVolumeClaim:
        claimName: fs-rbd-pvc
        readOnly: false
