---
- name: Check if the repository exists | yum {{ item.type }} repository ({{ item.name }})
  uri:
    url: "{{ nexus_main_url }}/service/rest/v1/repositories/yum/{{ item.type }}/{{ item.name }}"
    method: GET
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: false
  register: repo_check_response
  failed_when: repo_check_response.status not in [200, 404]
  ignore_errors: true
  tags:
    - setup_nexus
    - config_nexus
    - create_yum_repo

- name: Create yum {{ item.type }} repository ({{ item.name }})
  uri:
    url: "{{ nexus_main_url }}/service/rest/v1/repositories/yum/{{ item.type }}"
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    method: POST
    force_basic_auth: yes
    status_code: 201
    validate_certs: false
    body_format: json
    headers:
      Content-Type: "application/json"
    body: >-
      {
        "name": "{{ item.name }}",
        "online": true,
        "storage": {
          "blobStoreName": "{{ item.blob }}",
          "strictContentTypeValidation": true
          {% if item.type == 'hosted' %}
          ,
          "writePolicy": "{{ item.write_policy | default('ALLOW_ONCE') }}"
        },
        "component": {
          "proprietaryComponents": true
          {% endif %}
        },
        "cleanup": {
          "policyNames": ["{{ item.cleanup_policy }}"]
        },
        "yum": {
          "repodataDepth": "{{ item.repodata_depth | default(5) }}",
          "deployPolicy": "STRICT"
        {% if item.type == 'proxy' %}
        },
        "proxy": {
          "remoteUrl": "{{ item.remote_url }}",
          "contentMaxAge": 1440,
          "metadataMaxAge": 1440
        },
        "negativeCache": {
          "enabled": true,
          "timeToLive": 1440
        },
        "routingRule": "string",
        "httpClient": {
          "blocked": false,
          "autoBlock": false,
          "connection": {
            "retries": "",
            "userAgentSuffix": "",
            "timeout": "",
            "enableCircularRedirects": false,
            "enableCookies": false
          }
        {% endif %}
        }
      }
  when: repo_check_response.status != 200
  tags:
    - setup_nexus
    - config_nexus
    - create_yum_repo
