networks:
  proxy:
    name: proxy
    external: true
  app:
    name: app
    external: true

volumes:
  gitlab_config:
    name: gitlab_config
  gitlab_data:
    name: gitlab_data
  gitlab_log:
    name: gitlab_log
  gitlab_backups:
    name: gitlab_backups

services:
  gitlab:
    image: gitlab/gitlab-ce:${IMAGE_TAG}
    container_name: gitlab
    hostname: ${GITLAB_EXTERNAL_DOMAIN}
    restart: ${RESTART_POLICY}
    extra_hosts:
      - "objectstore.ceph.testbed.moh:192.168.59.122"
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_backups:/var/opt/gitlab/backups
      - gitlab_config:/etc/gitlab
    networks:
      - proxy
      - app
    ports:
      - "22:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-git.rule=Host(`${GITLAB_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.http-git.entrypoints=web"
      - "traefik.http.routers.git.rule=Host(`${GITLAB_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.git.entrypoints=web-secure"
      - "traefik.http.routers.git.tls=true"
      #- "traefik.http.routers.git.tls.certresolver=myresolver"
      - "traefik.http.routers.git.service=git"
      - "traefik.http.services.git.loadBalancer.server.port=80"
      - "traefik.http.routers.http-reg.rule=Host(`${GITLAB_REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.http-reg.entrypoints=web"
      - "traefik.http.routers.reg.rule=Host(`${GITLAB_REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.reg.entrypoints=web-secure"
      - "traefik.http.routers.reg.tls=true"
      #- "traefik.http.routers.reg.tls.certresolver=myresolver"
      - "traefik.http.routers.reg.service=reg"
      - "traefik.http.services.reg.loadBalancer.server.port=5001"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Gitlab external domain
        external_url 'https://${GITLAB_EXTERNAL_DOMAIN}'

        # Gitlab root password
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
        gitlab_rails['display_initial_root_password'] = false
        gitlab_rails['store_initial_root_password'] = false

        # Gitlab Nginx config
        nginx['enable'] = true
        nginx['client_max_body_size'] = '1024m'
        nginx['redirect_http_to_https'] = false
        nginx['gzip_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # nginx['proxy_cache'] = 'gitlab'
        nginx['proxy_protocol'] = false
        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        # GitLab email server configuration
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

        # Gitlab ban attack
        gitlab_rails['rack_attack_git_basic_auth'] = {
          'enabled' => true,
          'ip_whitelist' => ["127.0.0.1"],
          'maxretry' => 10,
          'findtime' => 60,
          'bantime' => 3600
        }

        # Gitlab backup configuration
        gitlab_rails['manage_backup_path'] = true
        gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
        gitlab_rails['backup_archive_permissions'] = 0644
        gitlab_rails['backup_keep_time'] = 604800
        gitlab_rails['env'] = {
            "SKIP" => "registry"
        }
        gitlab_rails['backup_upload_connection'] = {
          'provider' => 'AWS',
          'region' => 'eu-west-1',
          'aws_access_key_id' => '${BACKUP_S3_ACCESS_KEY}',
          'aws_secret_access_key' => '${BACKUP_S3_SECRET_KEY}',
          'endpoint' => '${BACKUP_S3_ENDPOINT}',
          'path_style' => true
        }
        gitlab_rails['backup_upload_remote_directory'] = '${BACKUP_S3_BUCKET}'
        gitlab_rails['backup_multipart_chunk_size'] = 104857600

        # GitLab registry configuration
        registry_external_url 'https://${GITLAB_REGISTRY_DOMAIN}'
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5001
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        # S3 storage configuration for Registry Backend
        registry['storage'] = {
            's3' => {
              'region' => 'us-east-1',
              'accesskey' => '${REGISTRY_S3_ACCESS_KEY}',
              'secretkey' => '${REGISTRY_S3_SECRET_KEY}',
              'bucket' => '${REGISTRY_S3_BUCKET}',
              'regionendpoint' => '${REGISTRY_S3_ENDPOINT}'
            }
          }

        # Gitlab disable unused services
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        pgbouncer_exporter['enable'] = false
        gitlab_exporter['enable'] = false
        prometheus_monitoring['enable'] = false
        letsencrypt['enable'] = false
        prometheus['enable'] = false
        monitoring_role['enable'] = false
        alertmanager['enable'] = false
